// Static UI copy + config (persona-independent). Centralised here so screens read
// labels/config from one content surface rather than scattered data consts.
export {
  HOME, ACCOUNTS_PAGE, ACCOUNT_DETAIL, ACCOUNT_MORE, SETTINGS, CONVERT, CONVERTER,
  CONVERT_MAIN, CONVERSIONS, CARD, CARD_ACTIONS, CARD_SECTIONS, CARD_SETTINGS,
  CARD_APPLE_PAY, CARD_INSIGHTS, PAYMENTS_SECTIONS, PAYMENTS_ACTIONS, PLACEHOLDERS,
  EXCHANGE_RATES, RATES_PER_AUD, TOP_CURRENCIES, ALL_CURRENCIES, AVAILABLE_BALANCE,
  TOTAL_BALANCE, QUICK_ACTIONS,
} from './data';
